FROM python:3.7-alpine

RUN mkdir /app
WORKDIR /app
ADD src/requirements.txt /app
ADD src/server.py /app
RUN pip install -r /app/requirements.txt
EXPOSE 8000
CMD ["gunicorn"  , "--bind", "0.0.0.0:8000", "server:app"]
