version: "3"
services:
  app:
    container_name: containerize_app_1
    image: app
    ports:
      - 8000:8000
  nginx:
    container_name: containerize_nginx_1
    image: nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - app
